# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xM8oGSRz-nUUR3j5leScxai0IZWOOSsZ
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("BASE_DE_DATOS.csv", on_bad_lines='skip')
df.head()

df = df.dropna(axis=1, how='all')
df = df.dropna(axis=0, how='all')
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df = df.fillna("Desconocido")
df.head()

df.to_csv("BASE_DE_DATOS_LIMPIA.csv", index=False)